services:
  - type: web
    name: sios
    runtime: static
    plan: free
    buildCommand: echo sios
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
